name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "backend/**" ]
    
  workflow_dispatch:
  
jobs:
  CI-CD:
    name: Backend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
        
      - name: Install Dependencies
        run: cd backend; npm install; tar -cvf deploy.tar ../backend
        
      - name: Shutdown Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ./kill.sh
            sudo rm -rf backend
            exit
        
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "backend/deploy.tar"
          target: "/home/ubuntu"
          strip_components: 1
          
      - name: Unzip File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ./unzip.sh
            exit
            
      - name: Run Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pwd
            nohup node backend/src/app.js &
            exit
          
          
          
    
      
